# Generated by Django 4.2.11 on 2026-03-04 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('pto_engineer', 'Инженер ПТО'), ('head_pto', 'Начальник ПТО'), ('supplier', 'Поставщик')], default='pto_engineer', max_length=20, verbose_name='Роль'),
        ),
    ]
