# Generated by Django 4.2.11 on 2026-01-21 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wells', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название документа')),
                ('document_type', models.CharField(choices=[('technical_spec', 'Техническое задание'), ('report', 'Отчёт'), ('protocol', 'Протокол'), ('other', 'Прочее')], default='other', max_length=20, verbose_name='Тип документа')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Файл документа')),
                ('generated_docx', models.FileField(blank=True, null=True, upload_to='generated_reports/', verbose_name='Сгенерированный отчёт')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='wells.well', verbose_name='Скважина')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
