# Generated by Django 4.2.11 on 2026-01-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('technical_spec', 'Техническое задание'), ('report', 'Отчёт'), ('protocol', 'Протокол'), ('geology_report', 'Геологический отчёт'), ('drilling_program', 'Программа бурения'), ('completion_report', 'Акт завершения'), ('safety_plan', 'План по безопасности'), ('other', 'Прочее')], default='other', max_length=20, verbose_name='Тип документа'),
        ),
    ]
