# Generated by Django 4.2.11 on 2026-01-21 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Скважина №123-А', max_length=200, verbose_name='Название скважины')),
                ('field', models.CharField(max_length=200, verbose_name='Месторождение')),
                ('coordinates', models.CharField(blank=True, help_text='Географические координаты', max_length=100, verbose_name='Координаты')),
                ('depth', models.DecimalField(decimal_places=2, help_text='Проектная глубина в метрах', max_digits=10, verbose_name='Глубина (м)')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлено на согласование'), ('approved_head', 'Согласовано НПТО'), ('approved', 'Утверждено'), ('in_work', 'В работе'), ('drilling_completed', 'Бурение завершено'), ('archived', 'Архив')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('description', models.TextField(blank=True, help_text='Дополнительная информация о скважине', verbose_name='Описание')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wells_authored', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Скважина',
                'verbose_name_plural': 'Скважины',
                'ordering': ['-created_at'],
                'permissions': [('approve_well', 'Может согласовывать скважины'), ('generate_report', 'Может генерировать отчёты')],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', 'Согласовано'), ('rejected', 'Отклонено'), ('pending', 'Ожидает рассмотрения')], default='pending', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='wells.well', verbose_name='Скважина')),
            ],
            options={
                'verbose_name': 'Шаг согласования',
                'verbose_name_plural': 'Шаги согласования',
                'ordering': ['timestamp'],
                'unique_together': {('well', 'user', 'timestamp')},
            },
        ),
    ]
