# Generated by Django 4.2.11 on 2026-01-22 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлено на согласование'), ('approved_head', 'Согласовано НПТО'), ('rejected', 'Отклонено'), ('approved', 'Утверждено'), ('in_work', 'В работе'), ('drilling_completed', 'Бурение завершено'), ('archived', 'Архив')], default='draft', max_length=20, verbose_name='Статус'),
        ),
    ]
