# Generated by Django 4.2.11 on 2026-01-22 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wells', '0002_alter_well_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Создана'), ('updated', 'Обновлена'), ('status_changed', 'Изменён статус'), ('submitted', 'Отправлена на согласование'), ('approved', 'Согласована'), ('rejected', 'Отклонена'), ('deleted', 'Удалена')], max_length=20, verbose_name='Действие')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('old_value', models.TextField(blank=True, verbose_name='Старое значение')),
                ('new_value', models.TextField(blank=True, verbose_name='Новое значение')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='wells.well', verbose_name='Скважина')),
            ],
            options={
                'verbose_name': 'История изменений',
                'verbose_name_plural': 'История изменений',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WellAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='well_attachments/%Y/%m/', verbose_name='Файл')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('category', models.CharField(choices=[('photo', 'Фотография'), ('drawing', 'Чертёж'), ('report', 'Отчёт'), ('certificate', 'Сертификат'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='Размер (байт)')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='wells.well', verbose_name='Скважина')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('color', models.CharField(default='#0d6efd', help_text='HEX цвет, например #0d6efd', max_length=7, verbose_name='Цвет')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='wells.comment', verbose_name='Ответ на')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='wells.well', verbose_name='Скважина')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WellDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone', models.CharField(choices=[('design', 'Проектирование'), ('approval', 'Согласование'), ('drilling_start', 'Начало бурения'), ('drilling_end', 'Окончание бурения'), ('testing', 'Испытания'), ('commissioning', 'Ввод в эксплуатацию')], max_length=20, verbose_name='Веха')),
                ('planned_date', models.DateField(verbose_name='Плановая дата')),
                ('actual_date', models.DateField(blank=True, null=True, verbose_name='Фактическая дата')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершено')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='wells.well', verbose_name='Скважина')),
            ],
            options={
                'verbose_name': 'Дедлайн',
                'verbose_name_plural': 'Дедлайны',
                'ordering': ['planned_date'],
                'unique_together': {('well', 'milestone')},
            },
        ),
    ]
